src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/mainsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import profiles.urls
import accounts.urls
import deployments.urls
import fractal_tree.urls
#import canvasapp.urls
import portfolio.urls

import portfolio.views as portfolio_views

from . import views

urlpatterns = [
    #url(r'^$', portfolio.views.mainindex, name='mainindex'), # this was to point to other app, SUCCEEDED, but awkward
    url(r'^$', views.index, name='home'),
    #url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^portfolio/', include(portfolio.urls, namespace='portfolio')),
    url(r'^fractal_tree/', include(fractal_tree.urls, namespace='fractal_tree')),
    #url(r'^maze2d/', views.maze2d, name='maze2d'),
    #url(r'^canvasapp/', include(canvasapp.urls, namespace='canvasapp')),
    url(r'^deployments/', include(deployments.urls, namespace='deployments')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portfolio/urls.py
from django.conf.urls import patterns, url
from . import views


urlpatterns = [
	url(r'^$', views.mainindex, name='mainindex'),
	url(r'^iframe/(?P<appname>[a-zA-Z\_\-0-9]*)$', views.iframe, name='iframe'),
    url(r'^category/(?P<id>[0-9]*)$', views.list_category, name='list-category'),
    url(r'^show/(?P<id>[0-9]*)$', views.show_item, name='show-item'),
]

src/portfolio/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.timezone import now
from django_thumbs.db.models import ImageWithThumbsField

from mainsite.settings.base import DEPLOYMENT_CHOICES




class PortfolioCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    short_description = models.TextField(null=True)
    image = ImageWithThumbsField(null=True, sizes=((125,125),(200,200)))
    deployment_type = models.CharField(max_length=50, choices=DEPLOYMENT_CHOICES, default='canvasapp')

    def __unicode__(self):
        return self.name

    def num_items(self):
        items = PortfolioItem.objects.filter(category__id=self.id)
        return len(items)

class PortfolioItem(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=500, blank=True)
    category = models.ForeignKey(PortfolioCategory)
    description = models.TextField()
    sourcecode = models.URLField()
    image = ImageWithThumbsField(null=True, sizes=((125,125),(200,200)))
    year = models.IntegerField()
    month = models.IntegerField()

    def __unicode__(self):
        return self.title


class ImageGallery(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

class ImageModel(models.Model):
    image = ImageWithThumbsField(sizes=((125,125),(200,200)))
    timestamp = models.DateTimeField(default=now, editable=False)
    gallery = models.ForeignKey(ImageGallery, null=True, related_name='images')



class ProprietaryPortfolioItem(PortfolioItem):

    company = models.CharField(max_length=100)
    gallery = models.ForeignKey(ImageGallery)

    def __init__(self, *args, **kwargs):
        super(ProprietaryPortfolioItem, self).__init__(*args, **kwargs)



class CanvasAppPortfolioItem(PortfolioItem):

    # script = models.CharField(max_length=100)
    # script_type = models.CharField(max_length=100)
    # appname = models.CharField(max_length=100, null=True)
    # deployment_name = models.CharField(max_length=100, null=True)

    script_mime_type = models.CharField(max_length=20, null=True)
    urlpath = models.CharField(max_length=100, null=True)

    def __init__(self, *args, **kwargs):
        super(CanvasAppPortfolioItem, self).__init__(*args, **kwargs)

    def __unicode__(self):
        return self.title


    

src/portfolio/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django import forms

from crispy_forms.helper import *
from crispy_forms.layout import *

from . import models
from fractal_tree.views import FractalTreeForm


class Canvas:
    
    def __init__(self, script, script_type):
        self.script = script
        self.script_type = script_type

class InteractiveCanvas(Canvas):

    def __init__(self, *args, **kwargs):
        super(InteractiveCanvas, self).__init__(*args, **kwargs)
        self.control_panel = FractalTreeForm()

def get_categories():
    categories = models.PortfolioCategory.objects.all()
    return categories


##############################################
### views



def mainindex(request):
    categories = models.PortfolioCategory.objects.all()
    return render(request, "index_topbar.html", {'categories': categories, 'iframe_src': '/deployments/breathing-cosines-light'})

def iframe(request, appname):
    template_name = "iframe.html"
    return render(request, "iframe.html", {'appname': appname})

# def index(request):
#   categories = models.PortfolioCategory.objects.all()
#   return render(request, "portfolio/index.html", {'categories': categories})



def list_category(request, id):
    try:
        category = models.PortfolioCategory.objects.get(pk=id)
    except models.PortfolioCategory.DoesNotExist:
        #return redirect('portfolio:mainindex')
        raise Exception("Category could not be found")

    if category.name == 'Proprietary':
        items = models.ProprietaryPortfolioItem.objects.filter(category__exact=id)
    else:
        items = models.PortfolioItem.objects.filter(category__exact=id).order_by('-id')
    return render(request, "portfolio/list_category.html", {'category': category, 'categories': get_categories(), 'items': items})

def show_item(request, id):
    try:
        item = models.PortfolioItem.objects.get(pk=id)
    except models.PortfolioItem.DoesNotExist:
        #return redirect('portfolio:mainindex')
        raise Exception("Item could not be found")

    #categories = self.get_category()
    if item.category.deployment_type == 'canvasapp':
        try:
            item = models.CanvasAppPortfolioItem.objects.get(pk=id)
        except models.CanvasAppPortfolioItem.DoesNotExist:
            #return redirect('portfolio:mainindex')
            raise Exception("Item could not be found")
        #item.script = "{% static '"+ item.script +"' %}"

        if item.urlpath:
            return render(request, "portfolio/show_item.html", {'categories': get_categories, 'item': item, 'iframe_src': item.urlpath})

    raise Exception("Neen needs to learn 404 response")

src/templates/portfolio/index.html
{% extends "index.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}Portfolio{% endblock %}



{% block pagecontent %}
<!-- Benefits of the Django application -->



<div class="text-page">

  <div class="page-header">
    <h1>Portfolio <small>categories</small></h1>
  </div>

  <div class="container-fluid bg-3 text-left">
   
    <!-- <div class="row"> -->
      {% for cat in categories %}
      <div class="col-sm-3">
        <div class="thumbnail">
          <a href="{% url 'portfolio:list-category' cat.id %}">
            <img src="{{ cat.image.url_200x200 }}" class="img-thumbnail" />
          </a>
          <div class="caption">
            <h3>{{ cat.name }} <div style="float:right;"><a href="{% url 'portfolio:list-category' cat.id %}" class="btn btn-primary" role="button">View &raquo;</a></div></h3>
            <p>{{ cat.description }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    <!-- </div> -->
  </div>
</div>

{% endblock pagecontent %}

src/templates/portfolio/list_category.html
{% extends "index.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}Portfolio{% endblock %}


{% block pagecontent %}
<!-- Benefits of the Django application -->

  

  <div class="page-header">
    <h1>Portfolio <small>{{ category.name }}</small></h1>
    <section>{{ category.description }}</section>
  </div>


  {% for item in items %}
  <div class="media">
    <div class="media-left media-top">
      <a href="#">
        <img class="media-object thumbnail" src="{{ item.image.url_200x200 }}" />
      </a>
    </div>
    <div class="media-body">
      <div class="media-heading">
        <h4>{{ item.title }} <br /><small>{{ item.subtitle }}</small></h4>
      </div>

      {% if category.deployment_type == 'description' %}
      <section>
        <strong>Company: </strong>{{ item.company }}<br />
        <strong>Year: </strong>{{ item.year }}<br />
      </section>
      {% endif %}
      <br />
      <p>{{ item.description }}</p>
      
      <a href="{% url 'portfolio:show-item' item.id %}" class="btn btn-primary" role="button">View &raquo;</a>

      {% if item.gallery %}
        <hr />
        <h4>Gallery of screenshots <span class="label label-primary pull-right">click to enlarge</span></h4>
        <div class="container-fluid">
        {% for image in item.gallery.images.all %}
          <img class="thumbnail floatmargins pull-left" src="{{ image.image.url_200x200 }}" />
        {% endfor %}
        </div>
      {% endif %}

    </div>
  </div>
  {% endfor %}



{% endblock pagecontent %}

src/templates/portfolio/show_item.html
{% extends 'index.html' %}

{% block extrahead %}

	{% if params %}
	<script type="text/coffeescript">


		window.FRACTAL_DIMENSION = {{ params.0 }}
		window.TRAPEZOIDAL_SECTIONS = {{ params.1 }}
		window.CHILDREN = {{ params.4 }}
		window.DEGREE1_COEFF = {{ params.2 }}
		window.DEGREE2_COEFF = {{ params.3 }}



	</script>
	{% endif %}


	<script type="text/javascript">

	
	$(document).ready(function () {
		$("#maincontent").remove();
	    $("iframe").each(function () {
	        //Using closures to capture each one
	        var iframe = $(this);
	        iframe.on("load", function () { //Make sure it is fully loaded
	            iframe.trigger("click");
	        });

	        iframe.click(function () {
	            iframe.focus();
	        });
	    });
	});

	</script>
	

	<!-- <script type="{{ item.script_mime_type }}" src="{{ item.urlpath }}"></script> -->
	
{% endblock %}


{% block pagecontent %}

{% endblock %}