src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/mainsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import profiles.urls
import accounts.urls
import deployments.urls
import fractal_tree.urls
#import canvasapp.urls
import portfolio.urls

import portfolio.views as portfolio_views

from . import views

urlpatterns = [
    #url(r'^$', portfolio.views.mainindex, name='mainindex'), # this was to point to other app, SUCCEEDED, but awkward
    url(r'^$', views.index, name='home'),
    #url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^portfolio/', include(portfolio.urls, namespace='portfolio')),
    url(r'^fractal_tree/', include(fractal_tree.urls, namespace='fractal_tree')),
    #url(r'^maze2d/', views.maze2d, name='maze2d'),
    #url(r'^canvasapp/', include(canvasapp.urls, namespace='canvasapp')),
    url(r'^deployments/', include(deployments.urls, namespace='deployments')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portfolio/urls.py
from django.conf.urls import patterns, url
from . import views


urlpatterns = [
	url(r'^$', views.mainindex, name='mainindex'),
	url(r'^iframe/(?P<appname>[a-zA-Z\_\-0-9]*)$', views.iframe, name='iframe'),
    url(r'^category/(?P<id>[0-9]*)$', views.list_category, name='list-category'),
    url(r'^show/(?P<id>[0-9]*)$', views.show_item, name='show-item'),
]

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/templates/_brandname.html
plerp.org

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">An Awesome Tagline Goes Here</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Scripts that MUST be loaded on all pages -->
    <script type="text/javascript" src="{% static 'site/js/coffee-script.js' %}"></script>
    <script type="text/javascript" src="{% static 'site/js/jQuery2.1.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'site/js/numeric-1.2.6.js' %}"></script>
    <script type="text/javascript" src="{% static 'site/js/underscore.js' %}"></script>
    <script type="text/javascript" src="{% static 'site/js/main.js' %}"></script>

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-52345664-1', 'auto');
      ga('send', 'pageview');

    </script>

  </head>

  <body {% block extrabodytag %}{% endblock %}>

    

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}{% endblock splash %}

    {% block container %}{% endblock container %}

    <!-- Site footer -->
    {% block footer %}{% endblock %}

    <div id="canvas_container">
      {% block bigcanvas %}{% endblock bigcanvas %}
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

  </body>
</html>

src/templates/base2.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body {% block extrabodytag %}{% endblock %}>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/general_iframe_js.html
{% extends "iframe.html" %}
{% load staticfiles %}

{% block extrahead %}
	

	<script type="text/javascript" src="{% static 'site/js/maze2d.js' %}"></script>
	
{% endblock %}

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block extrahead %}

<!-- <script type="text/javascript" src="{% static 'site/js/jQuery2.1.1.js' %}"></script> -->
<script type="text/javascript" src="{% static 'site/js/prism/prism.js' %}"></script>
<script type="text/javascript" src="{% static 'site/js/maze-bg/class.Maze.js' %}"></script>
<script type="text/javascript" src="{% static 'site/js/maze-bg/class.MazeSolver.js' %}"></script>
<script type="text/javascript" src="{% static 'site/js/MathJax2.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML' %}">
</script>

<script type="text/x-mathjax-config">
     MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
</script>



<script type="text/javascript">
        
    var Maze;
    var Canvas;
    var CanvasBox;
    var ctx;
    var solver;

    function startMaze() {

        //CanvasBox = $('#home_feature');

        var cellSize = 15;
        var screenwidth = $('#feature_col').width();
        var screenheight = $(window).height() - 50;

        Canvas = document.getElementById('headermaze');
        
        Canvas.width = screenwidth;
        Canvas.height = screenheight;

        var mx = Math.floor((Canvas.width) / cellSize);
        var my = Math.floor((Canvas.height) / cellSize);

        //document.body.appendChild(Canvas);
        ctx = Canvas.getContext("2d");
        //ctx = document.getCSSCanvasContext("2d", "mazecanvas", 

        Maze = new Maze(2, mx, my, cellSize);
        Maze.frameInterval = setInterval(Maze.renderStep, 30)

    }

    // $(function() {
    //     $('pre').each(function() {
    //         var text = $(this).html();
    //         var m = text.match(/\%\%[^\%]+\%\%/);
    //         if (m) {
    //             var lang = m[0].split('%').join('');
    //             var code = document.createElement('code');
    //             $(code).addClass('language-'+lang);
    //             $(code).css('white-space', 'pre');
    //             $(this).text('');
    //             $(code).text(
    //                 text.split(m[0]).join('')
    //                 .split('<br>').join("\n")
    //                 .split('&nbsp;').join(' ')
    //                 .split('&amp;').join('&')
    //                 .split('&lt;').join('<')
    //                 .split('&gt;').join('>')
    //                 );
    //             $(this).replaceWith($(code));
    //         }
    //     });
    // });
   
   

    

</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52345664-1', 'auto');
  ga('send', 'pageview');

</script>

{% endblock %}


{% block extrabodytag %}onload="startMaze();"{% endblock %}


{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}




{% block container %}

<div class="raw-container">

  
    <div class="row">
      <div id="feature_col" class="col-sm-5">
          <div id="home_feature">
            <canvas id="headermaze"></canvas>
          </div>
      </div>
      <div class="col-sm-7">

        <div class="page-header">
          <h1>Portfolio <small>categories</small></h1>
        </div>

         <div class="well"><em>
         The following is an interactive portfolio sampling work of computer <br />
         programmer and mathematician, Nino P. Cocchiarella.  </em></div>
   
     <!--  <div class="container-fluid bg-3 text-left">
      {% for cat in categories %}
      <div class="col-sm-6">
        <div class="thumbnail">
          <a href="{% url 'portfolio:list-category' cat.name %}">
            <img src="{{ cat.image.url_200x200 }}" class="img-thumbnail" />
          </a>
          <div class="caption text-left">
            <h3>{{ cat.name }}</h3>
            <p>{{ cat.description }}</p>
            <a href="{% url 'portfolio:list-category' cat.name %}" class="btn btn-primary" role="button">View &raquo;</a>
          </div>
        </div>
      </div>
      {% endfor %}
      </div> -->

    {% for cat in categories %}
    <div class="media">
      <div class="media-left media-top">
        <a href="{% url 'portfolio:list-category' cat.name %}">
          <img class="media-object thumbnail" src="{{ cat.image.url_200x200 }}" />
        </a>
      </div>
      <div class="media-body">
        <div class="media-heading">
          <h4>{{ cat.name }}</h4>
        </div>

        <div class="caption">
          <p>{{ cat.description }}</p>
          <a href="{% url 'portfolio:list-category' cat.name %}" class="btn btn-primary" role="button">View &raquo;</a>
        </div>

      </div>
    </div>
    {% endfor %}
  
      </div>
      <!-- <div class="col-sm-3">
        <aside>
        sdfgslkdjfgsdlkfj
        </aside>
      </div> -->
    </div>

  
  
  
</div>

{% endblock container %}

{% block scripts %}
<!-- <script src="{% static 'site/js/site.js' %}"></script> -->
{% endblock scripts %}


{% block footer %}

{% endblock %}

src/templates/iframe.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="description" content="{% block description %}{% endblock description %}">
	    <meta name="author" content="Arun Ravindran">
	    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

	    {% block extrahead %}
	        


	    {% endblock extrahead %}

	    <script type="text/javascript" src="{% static 'site/js/coffee-script.js' %}"></script>
    	<script type="text/javascript" src="{% static 'site/js/jQuery2.1.1.js' %}"></script>
    	<script type="text/javascript" src="{% static 'site/js/numeric-1.2.6.js' %}"></script>
    	<script type="text/javascript" src="{% static 'site/js/underscore.js' %}"></script>
    	
    	<!--<script type="text/coffeescript" src="{% static 'site/coffeescript/iframe.coffee' %}"></script>-->
    	<script type="text/javascript" src="{% static 'site/js/iframe.js' %}"></script>

    	<!-- Bootstrap core CSS -->
	    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

	    <!-- Custom styles for this site -->
	    {% block styles %}
	    <link href="{% static 'site/css/iframe.css' %}" rel="stylesheet">
	    {% endblock styles %}

	    


	</head>

	<body>
	
	</body>
</html>

src/templates/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block extrahead %}

<!-- <script type="text/javascript" src="{% static 'site/js/jQuery2.1.1.js' %}"></script> -->
<!-- <script type="text/javascript" src="{% static 'site/js/prism/prism.js' %}"></script> -->
<!-- <script type="text/javascript" src="{% static 'site/js/maze-bg/class.Maze.js' %}"></script> -->
<!-- `<script type="text/javascript" src="{% static 'site/js/maze-bg/class.MazeSolver.js' %}"></script> -->
<!-- `<script type="text/javascript" src="{% static 'site/js/MathJax2.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML' %}"> -->
<!-- </script> -->

<!--
<script type="text/x-mathjax-config">
     MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
</script>
-->
{% endblock %}





{% block navbar-right %}
  {% if not user.is_authenticated %}
  <a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}






{% block container %}

<div class="container-fluid">
    <div class="row row-offcanvas row-offcanvas-left active">


      <div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">
         
        <h3 class="mute">Portfolio</h3>
        <div class="list-group">
          {% for cat in categories %}
            <a href="#" class="list-group-item">{{ cat.name }}<span class="badge">{{ cat.num_items }}</span></a>
          {% endfor %}
        </div>
      </div>



      
      <div class="col-sm-9 col-md-10 main" id="maincontent">
  
        <!--toggle sidebar button-->
        <p class="visible-xs">
          <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">
            <i class="glyphicon glyphicon-chevron-left"></i></button>
        </p>

        {% block pagecontent %}
        <div class="row placeholders">
          {% for cat in categories %}
            <div class="col-xs-6 col-sm-3 placeholder text-center">
              
                <a href="{% url 'portfolio:list-category' cat.id %}">
                  <img class="center-block img-responsive img-circle img-circle-border" src="{{ cat.image.url_200x200 }}" />
                </a>
                
                <h4>{{ cat.name }}</h4>
                <!-- <span class="text-muted">{{ cat.short_description }}</span> -->
              </div>
            
          {% endfor %}  
        </div>
        {% endblock pagecontent %}
         
          
      </div><!--/row-->


  </div>
</div>




        

{% endblock container %}

{% block scripts %}

{% endblock scripts %}


{% block footer %}

{% endblock %}

{% block bigcanvas %}
  {% if iframe_src %}
    <iframe id="big-canvas" scrolling="no" src="{{ iframe_src }}"></iframe>
  {% endif %}
{% endblock bigcanvas %}

src/templates/index_topbar.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block extrahead %}
{% endblock %}










{% block container %}

<div class="container-fluid">
    


     <!--  <div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">
         
        <h3 class="mute">Portfolio</h3>
        <div class="list-group">
          {% for cat in categories %}
            <a href="#" class="list-group-item">{{ cat.name }}<span class="badge">{{ cat.num_items }}</span></a>
          {% endfor %}
        </div>
      </div> -->



      
      <div id="maincontent">
  
        {% block pagecontent %}
        <div class="row placeholders poop">
          {% for cat in categories %}
            <div class="col-xs-6 col-sm-3 placeholder text-center">
              
                <a href="{% url 'portfolio:list-category' cat.id %}">
                  <img class="center-block img-responsive img-circle img-circle-border" src="{{ cat.image.url_200x200 }}" />
                </a>
                
                <h4>{{ cat.name }}</h4>
                <!-- <span class="text-muted">{{ cat.short_description }}</span> -->
              </div>
            
          {% endfor %}  
        </div>
        {% endblock pagecontent %}
         
          
      </div><!--/row-->

</div>



{% endblock container %}

{% block scripts %}
{% endblock scripts %}


{% block footer %}
{% endblock %}

{% block bigcanvas %}
  {% if iframe_src %}
    <iframe id="big-canvas" scrolling="no" src="{{ iframe_src }}"></iframe>
  {% endif %}
{% endblock bigcanvas %}